spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:~/productcomparison
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddlAuto: create-drop